FROM nginx:latest

MAINTAINER joramuns

COPY ./server/nginx.conf /etc/nginx
COPY ./server/mini-server.c /etc/

RUN apt update && \
    apt install gcc libfcgi-dev spawn-fcgi -y && \
    gcc /etc/mini-server.c -o /etc/mini-server.fcgi -lfcgi

CMD spawn-fcgi -p 8080 /etc/mini-server.fcgi && \
    nginx

